[package]
name = "solv"
version = "0.1.0"
authors = ["Benjamin Kircher <benjamin.kircher@gmail.com>"]
edition = "2018"

[[bin]]
name = "whatrequires"
path = "examples/whatrequires.rs"

[dependencies]
libc = "0.2.43"  # Same as rust-libc-devel package
